sudo: required
env:
  global:
  - DIST_REPO="f5-sphinx-theme"
services:
- docker
language: python
python:
- '2.7'
before_install:
- git config --global user.email "OpenStack_TravisCI@f5.com"
- git config --global user.name "Travis F5 Openstack"
install:
- gem install html-proofer
- npm install -g css-validator
- pip install ./
script:
- htmlproofer --check_html --checks-to-ignore "LinkCheck,ImageCheck,ScriptCheck" --report_invalid_tags --report-script-embeds f5_sphinx_theme/
- css-validator f5_sphinx_theme/static/css/custom.css

addons:
  artifacts:
    paths:
    - $HOME/
deploy:
- provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  server: https://pypi.python.org.pypi
  on:
    tags: true
  skip_cleanup: true
